language: python

python: 3.5

dist: trusty
sudo: required

env:
  global:
    - TRAVIS_NODE_VERSION="6"

services:
    - mongodb
    - redis-server

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    - elasticsearch-2.x
    packages:
    - mongodb-org-server
    - elasticsearch

cache:
    - pip
    - npm

before_install:
    - node --version
    - sudo apt-get purge elasticsearch
    - sudo apt-get install -t stable elasticsearch
    - sudo service elasticsearch restart

install:
    - npm install
    - cd server && pip install -q -r requirements.txt && cd ..
    - chmod a+x server/scripts/install-highcharts-export-server.sh
    - pip install -e .

script:
    - cd server && python3 -u -m analytics.reports.highcharts_server &
    - make testpy
    - make testjs

after_success:
    - coveralls
